import { OptionSelect } from "./style";

export default function Countrys(){
    return (
    <>
        <OptionSelect value="0"></OptionSelect>
        <OptionSelect value="1">Anguila</OptionSelect>
        <OptionSelect value="2">Antárctica</OptionSelect>
        <OptionSelect value="3">Bonaire, Santo Eustáquio e Saba</OptionSelect>
        <OptionSelect value="4">Curaçau</OptionSelect>
        <OptionSelect value="5">Geórgia do Sul e Ilhas Sandwich</OptionSelect>
        <OptionSelect value="6">Gibraltar</OptionSelect>
        <OptionSelect value="7">Gronelândia</OptionSelect>
        <OptionSelect value="8">Guadalupe</OptionSelect>
        <OptionSelect value="9">Guam</OptionSelect>
        <OptionSelect value="10">Guernsey</OptionSelect>
        <OptionSelect value="11">Guiné</OptionSelect>
        <OptionSelect value="12">Hong Kong</OptionSelect>
        <OptionSelect value="13">Ilha Bouvet</OptionSelect>
        <OptionSelect value="14">Ilha Christmas</OptionSelect>
        <OptionSelect value="15">Ilha de Man</OptionSelect>
        <OptionSelect value="16">Ilha Heard e Ilhas Mcdonald</OptionSelect>
        <OptionSelect value="17">Ilha Norfolk</OptionSelect>
        <OptionSelect value="18">Ilhas Aland</OptionSelect>
        <OptionSelect value="19">Ilhas Caimão</OptionSelect>
        <OptionSelect value="20">Ilhas Cocos (Keeling)</OptionSelect>
        <OptionSelect value="21">Ilhas Cook</OptionSelect>
        <OptionSelect value="22">Ilhas Falkland (Malvinas)</OptionSelect>
        <OptionSelect value="23">Ilhas Marianas do Norte</OptionSelect>
        <OptionSelect value="24">Ilhas Marshall</OptionSelect>
        <OptionSelect value="25">Ilhas Menores Distantes dos Estados Unidos</OptionSelect>
        <OptionSelect value="26">Ilhas Turcas e Caicos</OptionSelect>
        <OptionSelect value="27">Ilhas Virgens (Britânicas)</OptionSelect>
        <OptionSelect value="28">Ilhas Virgens (Estados Unidos)</OptionSelect>
        <OptionSelect value="29">Jersey</OptionSelect>
        <OptionSelect value="30">Mayotte</OptionSelect>
        <OptionSelect value="31">Monserrate</OptionSelect>
        <OptionSelect value="32">Montenegro</OptionSelect>
        <OptionSelect value="33">Nauru</OptionSelect>
        <OptionSelect value="34">Niue</OptionSelect>
        <OptionSelect value="35">Nova Caledónia</OptionSelect>
        <OptionSelect value="36">Palau</OptionSelect>
        <OptionSelect value="37">Papuásia-Nova Guiné</OptionSelect>
        <OptionSelect value="38">Peru</OptionSelect>
        <OptionSelect value="39">Pitcairn</OptionSelect>
        <OptionSelect value="40">Polónia</OptionSelect>
        <OptionSelect value="41">Reunião</OptionSelect>
        <OptionSelect value="42">Saara Ocidental</OptionSelect>
        <OptionSelect value="43">Samoa Americana</OptionSelect>
        <OptionSelect value="44">Santa Helena, Ascensão e Tristão da Cunha</OptionSelect>
        <OptionSelect value="45">Santa Sé (Cidade Estado do Vaticano)</OptionSelect>
        <OptionSelect value="46">São Bartolomeu</OptionSelect>
        <OptionSelect value="47">São Martinho (parte francesa)</OptionSelect>
        <OptionSelect value="48">São Martinho (parte holandesa)</OptionSelect>
        <OptionSelect value="49">São Pedro e Miquelon</OptionSelect>
        <OptionSelect value="50">São Vicente e Granadinas</OptionSelect>
        <OptionSelect value="51">Sérvia</OptionSelect>
        <OptionSelect value="52">Sudão do Sul</OptionSelect>
        <OptionSelect value="53">Svalbard e a Ilha de Jan Mayen</OptionSelect>
        <OptionSelect value="54">Taiwan (Província da China)</OptionSelect>
        <OptionSelect value="55">Território Britânico do Oceano Índico</OptionSelect>
        <OptionSelect value="56">Territórios Franceses do Sul</OptionSelect>
        <OptionSelect value="57">Tokelau</OptionSelect>
        <OptionSelect value="58">Wallis e Futuna (Ilhas)</OptionSelect>
        <OptionSelect value="59">Outros países Africanos</OptionSelect>
        <OptionSelect value="60">Outros países Americanos</OptionSelect>
        <OptionSelect value="61">Outros países Asiáticos</OptionSelect>
        <OptionSelect value="62">Outros países da Oceania</OptionSelect>
        <OptionSelect value="63">Outros países Europeus</OptionSelect>
        <OptionSelect value="64">Regiões polares</OptionSelect>
        <OptionSelect value="65">Macedónia (Antiga República Jugoslava da Macedónia)</OptionSelect>
        <OptionSelect value="66">Antígua e Barbuda</OptionSelect>
        <OptionSelect value="67">Aruba</OptionSelect>
        <OptionSelect value="68">Austrália</OptionSelect>
        <OptionSelect value="69">Barbados</OptionSelect>
        <OptionSelect value="70">Belize</OptionSelect>
        <OptionSelect value="71">Bermudas</OptionSelect>
        <OptionSelect value="72">Bósnia-Herzegovina</OptionSelect>
        <OptionSelect value="73">Burkina Faso</OptionSelect>
        <OptionSelect value="74">Canadá</OptionSelect>
        <OptionSelect value="75">Bahamas</OptionSelect>
        <OptionSelect value="76">Suíça</OptionSelect>
        <OptionSelect value="77">Congo</OptionSelect>
        <OptionSelect value="78">Congo (República Democrática do Congo)</OptionSelect>
        <OptionSelect value="79">Coreia (República Popular Democrática da Coreia do Norte)</OptionSelect>
        <OptionSelect value="80">Coreia (República Popular Democrática da Coreia do Sul)</OptionSelect>
        <OptionSelect value="81">Dominica</OptionSelect>
        <OptionSelect value="82">Emiratos Árabes Unidos</OptionSelect>
        <OptionSelect value="83">Eritreia</OptionSelect>
        <OptionSelect value="84">Micronésia (Estados Federados da Micronésia)</OptionSelect>
        <OptionSelect value="85">Estados Unidos</OptionSelect>
        <OptionSelect value="86">México</OptionSelect>
        <OptionSelect value="87">Malásia</OptionSelect>
        <OptionSelect value="88">Rússia (Federação da Rússia)</OptionSelect>
        <OptionSelect value="89">Luxemburgo</OptionSelect>
        <OptionSelect value="90">Líbia (Jamahiriya Árabe da Líbia)</OptionSelect>
        <OptionSelect value="91">Granada</OptionSelect>
        <OptionSelect value="92">Guiana Francesa</OptionSelect>
        <OptionSelect value="93">Ilhas Faroé</OptionSelect>
        <OptionSelect value="94">Ilhas Salomão</OptionSelect>
        <OptionSelect value="95">Irlanda</OptionSelect>
        <OptionSelect value="96">Israel</OptionSelect>
        <OptionSelect value="97">Jamaica</OptionSelect>
        <OptionSelect value="98">Japão</OptionSelect>
        <OptionSelect value="99">Kuwait</OptionSelect>
        <OptionSelect value="100">Martinica</OptionSelect>
        <OptionSelect value="101">Mongólia</OptionSelect>
        <OptionSelect value="102">Nova Zelândia</OptionSelect>
        <OptionSelect value="103">Polinésia Francesa</OptionSelect>
        <OptionSelect value="104">Porto Rico</OptionSelect>
        <OptionSelect value="105">Andorra</OptionSelect>
        <OptionSelect value="106">Liechtenstein</OptionSelect>
        <OptionSelect value="107">Mónaco</OptionSelect>
        <OptionSelect value="108">Catar</OptionSelect>
        <OptionSelect value="109">Macau</OptionSelect>
        <OptionSelect value="110">Arábia Saudita</OptionSelect>
        <OptionSelect value="111">Bélgica</OptionSelect>
        <OptionSelect value="112">Dinamarca</OptionSelect>
        <OptionSelect value="113">Espanha</OptionSelect>
        <OptionSelect value="114">Noruega</OptionSelect>
        <OptionSelect value="115">Suazilândia</OptionSelect>
        <OptionSelect value="116">Suécia</OptionSelect>
        <OptionSelect value="117">Tailândia</OptionSelect>
        <OptionSelect value="118">Marrocos</OptionSelect>
        <OptionSelect value="119">Bahrain</OptionSelect>
        <OptionSelect value="120">Butão</OptionSelect>
        <OptionSelect value="121">Camboja</OptionSelect>
        <OptionSelect value="122">Lesoto</OptionSelect>
        <OptionSelect value="123">Nepal</OptionSelect>
        <OptionSelect value="124">Países Baixos</OptionSelect>
        <OptionSelect value="125">Jordânia</OptionSelect>
        <OptionSelect value="126">Reino Unido</OptionSelect>
        <OptionSelect value="127">Síria (República Árabe da Síria)</OptionSelect>
        <OptionSelect value="128">Iémen</OptionSelect>
        <OptionSelect value="129">Egipto</OptionSelect>
        <OptionSelect value="130">Argélia</OptionSelect>
        <OptionSelect value="131">Venezuela, República Bolivariana da Venezuela</OptionSelect>
        <OptionSelect value="132">Centro-Africana (República)</OptionSelect>
        <OptionSelect value="133">República Checa</OptionSelect>
        <OptionSelect value="134">Guiana</OptionSelect>
        <OptionSelect value="135">África do Sul</OptionSelect>
        <OptionSelect value="136">Albânia</OptionSelect>
        <OptionSelect value="137">Argentina</OptionSelect>
        <OptionSelect value="138">Arménia</OptionSelect>
        <OptionSelect value="139">Áustria</OptionSelect>
        <OptionSelect value="140">Bielorrússia</OptionSelect>
        <OptionSelect value="141">Bolívia, Estado Plurinacional da Bolívia</OptionSelect>
        <OptionSelect value="142">Bulgária</OptionSelect>
        <OptionSelect value="143">Colômbia</OptionSelect>
        <OptionSelect value="144">Costa do Marfim</OptionSelect>
        <OptionSelect value="145">Costa Rica</OptionSelect>
        <OptionSelect value="146">Croácia</OptionSelect>
        <OptionSelect value="147">Eslováquia</OptionSelect>
        <OptionSelect value="148">Eslovénia</OptionSelect>
        <OptionSelect value="149">Estónia</OptionSelect>
        <OptionSelect value="150">Finlândia</OptionSelect>
        <OptionSelect value="151">Gâmbia</OptionSelect>
        <OptionSelect value="152">Geórgia</OptionSelect>
        <OptionSelect value="153">Guatemala</OptionSelect>
        <OptionSelect value="154">Guiné Equatorial</OptionSelect>
        <OptionSelect value="155">Hungria</OptionSelect>
        <OptionSelect value="156">Índia</OptionSelect>
        <OptionSelect value="157">Indonésia</OptionSelect>
        <OptionSelect value="158">Islândia</OptionSelect>
        <OptionSelect value="159">Itália</OptionSelect>
        <OptionSelect value="160">Letónia</OptionSelect>
        <OptionSelect value="161">Libéria</OptionSelect>
        <OptionSelect value="162">Lituânia</OptionSelect>
        <OptionSelect value="163">Moldova (República de Moldova)</OptionSelect>
        <OptionSelect value="164">Namíbia</OptionSelect>
        <OptionSelect value="165">Nicarágua</OptionSelect>
        <OptionSelect value="166">Roménia</OptionSelect>
        <OptionSelect value="167">Serra Leoa</OptionSelect>
        <OptionSelect value="168">Tunísia</OptionSelect>
        <OptionSelect value="169">Turquia</OptionSelect>
        <OptionSelect value="170">Zâmbia</OptionSelect>
        <OptionSelect value="171">Filipinas</OptionSelect>
        <OptionSelect value="172">Honduras</OptionSelect>
        <OptionSelect value="173">Ilhas Fiji</OptionSelect>
        <OptionSelect value="174">Maldivas</OptionSelect>
        <OptionSelect value="175">Maurícias</OptionSelect>
        <OptionSelect value="176">Seychelles</OptionSelect>
        <OptionSelect value="177">Angola</OptionSelect>
        <OptionSelect value="178">Cuba</OptionSelect>
        <OptionSelect value="179">El Salvador</OptionSelect>
        <OptionSelect value="180">Madagáscar</OptionSelect>
        <OptionSelect value="181">Malta</OptionSelect>
        <OptionSelect value="182">Moçambique</OptionSelect>
        <OptionSelect value="183">São Marino</OptionSelect>
        <OptionSelect value="184">Singapura</OptionSelect>
        <OptionSelect value="185">Trindade e Tobago</OptionSelect>
        <OptionSelect value="186">Timor Leste</OptionSelect>
        <OptionSelect value="187">Etiópia</OptionSelect>
        <OptionSelect value="188">Sri Lanka</OptionSelect>
        <OptionSelect value="189">Azerbaijão</OptionSelect>
        <OptionSelect value="190">Benim</OptionSelect>
        <OptionSelect value="191">Botswana</OptionSelect>
        <OptionSelect value="192">Burundi</OptionSelect>
        <OptionSelect value="193">Cazaquistão</OptionSelect>
        <OptionSelect value="194">Chade</OptionSelect>
        <OptionSelect value="195">Chile</OptionSelect>
        <OptionSelect value="196">Chipre</OptionSelect>
        <OptionSelect value="197">Jibuti</OptionSelect>
        <OptionSelect value="198">Equador</OptionSelect>
        <OptionSelect value="199">Gabão</OptionSelect>
        <OptionSelect value="200">Gana</OptionSelect>
        <OptionSelect value="201">Haiti</OptionSelect>
        <OptionSelect value="202">Iraque</OptionSelect>
        <OptionSelect value="203">Kiribati</OptionSelect>
        <OptionSelect value="204">Líbano</OptionSelect>
        <OptionSelect value="205">Malawi</OptionSelect>
        <OptionSelect value="206">Mali</OptionSelect>
        <OptionSelect value="207">Niger</OptionSelect>
        <OptionSelect value="208">Panamá</OptionSelect>
        <OptionSelect value="209">Paraguai</OptionSelect>
        <OptionSelect value="210">Quénia</OptionSelect>
        <OptionSelect value="211">Quirguizistão</OptionSelect>
        <OptionSelect value="212">Ruanda</OptionSelect>
        <OptionSelect value="213">Senegal</OptionSelect>
        <OptionSelect value="214">Sudão</OptionSelect>
        <OptionSelect value="215">Suriname</OptionSelect>
        <OptionSelect value="216">Tajiquistão</OptionSelect>
        <OptionSelect value="217">Togo</OptionSelect>
        <OptionSelect value="218">Uganda</OptionSelect>
        <OptionSelect value="219">Usbequistão</OptionSelect>
        <OptionSelect value="220">Vanuatu</OptionSelect>
        <OptionSelect value="221">Zimbabwe</OptionSelect>
        <OptionSelect value="222">República Dominicana</OptionSelect>
        <OptionSelect value="223">Camarões</OptionSelect>
        <OptionSelect value="224">Alemanha</OptionSelect>
        <OptionSelect value="225">Nigéria</OptionSelect>
        <OptionSelect value="226">Brasil</OptionSelect>
        <OptionSelect value="227">França</OptionSelect>
        <OptionSelect value="228">Grécia</OptionSelect>
        <OptionSelect value="229">Mauritânia</OptionSelect>
        <OptionSelect value="230">Comores</OptionSelect>
        <OptionSelect value="231">Afeganistão</OptionSelect>
        <OptionSelect value="232">Irão (República Islâmica)</OptionSelect>
        <OptionSelect value="233">Paquistão</OptionSelect>
        <OptionSelect value="234">Uruguai</OptionSelect>
        <OptionSelect value="235">Laos (República Popular Democrática do Laos)</OptionSelect>
        <OptionSelect value="236">Bangladesh</OptionSelect>
        <OptionSelect value="237">Portugal</OptionSelect>
        <OptionSelect value="238">Vietname</OptionSelect>
        <OptionSelect value="239">Tanzânia, República Unida da Tanzânia</OptionSelect>
        <OptionSelect value="240">Samoa</OptionSelect>
        <OptionSelect value="241">Santa Lúcia</OptionSelect>
        <OptionSelect value="242">São Cristóvão e Nevis</OptionSelect>
        <OptionSelect value="243">Somália</OptionSelect>
        <OptionSelect value="244">Omã</OptionSelect>
        <OptionSelect value="245">Brunei Darussalam</OptionSelect>
        <OptionSelect value="246">Território Palestiniano Ocupado</OptionSelect>
        <OptionSelect value="247">Tonga</OptionSelect>
        <OptionSelect value="248">Turquemenistão</OptionSelect>
        <OptionSelect value="249">Tuvalu</OptionSelect>
        <OptionSelect value="250">Ucrânia</OptionSelect>
        <OptionSelect value="251">Myanmar</OptionSelect>
        <OptionSelect value="252">Cabo Verde</OptionSelect>
        <OptionSelect value="253">São Tomé e Príncipe</OptionSelect>
        <OptionSelect value="254">China</OptionSelect>
        <OptionSelect value="255">Guiné-Bissau</OptionSelect>
        <OptionSelect value="256">Países e territórios ignorados</OptionSelect>
    </>
    );
}